### ISSUE TITLE
compile error at make project

### ISSUE THREAD

**Issue by TheIdhem** [MohGanji/os-2#1]
hello!when ever I make you project I gave the compile error!what should I do?
![screen shot 2018-04-12 at 2 11 09 pm](https://user-images.githubusercontent.com/31737620/38669344-61b30918-3e5b-11e8-94ef-9b91d354d0e8.png)

**Comment by MohGanji** [comment]
updated.

**Comment by TheIdhem** [comment]
tnx!

**Comment by vmohir** [comment]
You are so help :+1:
